<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FixMaster.Identity.Application\FixMaster.Identity.Application.csproj" />
    <ProjectReference Include="..\..\..\Common\FixMaster.Common\FixMaster.Common.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
